folders:
  M_: /Materials
  SKM_: /Meshes/Skeletal
  SM_: /Meshes
  T_: /Textures
naming:
  prefixes:
    material: M_
    skeletal_mesh: SK_
    static_mesh: SM_
    texture: T_
  suffixes:
    static_mesh:
    skeletal_mesh: _SomeSuffix_Skeletal
    base_color: _BC
    metalness: _M
    normal: _N
    roughness: _R
textures:
  allowed_formats:
  - .png
  - .tga
  - .tiff
  max_file_size_mb: 50
  max_resolution: 2048
  require_power_of_two: true
